name: Build and Publish Electron App

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # Permiso para modificar releases

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            file_extension: exe
          - os: macos-latest
            file_extension: dmg

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build App
        run: npm run build:${{ contains(matrix.os, 'windows') && 'win' || 'mac' }}

      - name: Upload ONLY Generated Files to Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/*.${ { matrix.file_extension } }          # .exe o .dmg
            dist/*.${ { matrix.file_extension } }.blockmap  # Blockmaps
            dist/*.yml                                      # Metadata de updates
            dist/*.zip                                      # Si generas ZIPs
          tag_name: ${{ github.ref_name }}
          prerelease: false
          draft: false
