name: Build and Release eyep Binaries

on:
  push:
    tags:
      - 'v*'

env:
  NODE_VERSION: '20.x'

jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install electron-vite
        run: npm install -g electron-vite

      - name: Build and Release on macOS
        if: matrix.os == 'macos-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Ejecutando build para macOS"
          electron-vite build
          echo "Publicando para macOS"
          electron-builder --mac -p always

      - name: Build and Release on Windows
        if: matrix.os == 'windows-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Ejecutando build para Windows"
          npm run build
          echo "Publicando para Windows"
          electron-builder --win -p always
